# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-14 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='date_joined',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
