# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-28 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_carousel2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel1',
            options={'verbose_name_plural': 'Carousel1'},
        ),
        migrations.AlterModelOptions(
            name='carousel2',
            options={'verbose_name_plural': 'Carousel2'},
        ),
    ]
