# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-28 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_auto_20161028_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel1',
            name='price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='carousel2',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
